### ISSUE TITLE
Functions from mdgriffith/elm-ui missing from the docset

### ISSUE THREAD

**Issue by alexkorban** [kraklin/elm-docset#1]
Some functions show up in the docs on the package site, but not in the docset. 

Examples from mdgriffith/elm-ui that don't appear in the current version of the docset: 

- Element.Border.roundEach
- Element.Border.dotted
- Element.Background.tiledY
- Element.Font.size
- Element.Font.wordSpacing

**Comment by kraklin** [comment]
Looks like the docset is not generating item when it is last and without any comment as this is kind of consistent behaviour. So it looks like some off by 1 error is there. Thank you for noticing..

**Comment by kraklin** [comment]
So in the end the problem was with trailing `\n`'s in the docs of elm-ui. Thank you @alexkorban for noticing. The docset is rebuild and waiting to be accepted to Dash repository.
